[package]
name = "minimal_rust"
version = "0.1.0"
authors = ["Zachary Pierce <zpierce@polysync.io>"]
build = "build.rs"

[dependencies]

[[bin]]
name = "assignment"
path = "src/bin/assignment.rs"

[build-dependencies]
gcc = "0.3"
